### ISSUE TITLE
Network Connection

### ISSUE THREAD

**Issue by JaySt** [adoreits/adore-datatables#1]
The jQuery and CSS files seem not to be found despit the fact that they are where they are suppossed to be.

**Comment by JaySt** [comment]
I got the links working by zipping the plugin folder as "adore-datatables" and not "adore-datatables-master" .

**Comment by nirajkvinit** [comment]
You do not need "adore-datatables-master". Just download the zip and upload as a plugin. This plugin is still under construction! I created this just to test the functionality. More features and testing is under way. 

As far as your first comment, will test and update the code accordingly.

**Comment by nirajkvinit** [comment]
Issues has been fixed. Please download the plugin and test. 
Do create a ticket here to let me know any further issues.
