### ISSUE TITLE
Saving Datatable Problem

### ISSUE THREAD

**Issue by Marin-Matosevic** [adoreits/adore-datatables#2]
Hi,

first of all thank you for developing this plugin, everything seems to be alright except I'm having a problem with saving datatable (in dashboard).
When I hit 'Save Datatable' nothing happens. 
Do you have any idea what is causing this problem?

thanks!
Marin

**Comment by nirajkvinit** [comment]
Hello Marin! 
There are still more work to be done. Adore-Datatables settings page is still under construction. Which means you cannot create any new datatables yet. However, you can use the demo shortcode for testing the plugin.
Niraj Kumar

**Comment by me-nwa** [comment]
Hello 
Thank for developing this plugin, but there is a way to pass variable through url ??

**Comment by nirajkvinit** [comment]
Hello! Apology for late reply! I was away.
Can you please elaborate more on your issue? Give some more information to understand the context?
